Vagrant.configure("2") do |config|
    
    config.vm.provider "virtualbox" do |v|
        v.name = "formation_docker"
    end
    
    config.vm.box = "hashicorp/bionic64"
    
    config.vm.provision "docker" do |d|
        d.pull_images "alpine"
    end
end